spring.application.name=eurekaserverapp

server.port=8761
#Do not register itself
eureka.client.register-with-eureka=false

#Do not fetch registry
eureka.client.fetch-registry=false

#Set Service zone
eureka.client.service-url.defaultZone=http://localhost:8761/eureka