spring.application.name=apiagtewayapp

server.port=8888

#Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Do not register itself
eureka.client.register-with-eureka=true
#Do not fetch Registry
eureka.client.fetch-registry=true

# Gateway Discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


# auth service route
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# auction service route
spring.cloud.gateway.server.webflux.routes[1].id=auction-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://auctionservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auction/**

# bid service route
spring.cloud.gateway.server.webflux.routes[2].id=bid-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://bidservice
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/bid/**

# payment service route
spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://paymentservice
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/payment/**

# JWT secret - must match authservice exactly
bidvelocity.jwt.secret=BidVelocityAuctionEngineSuperSecretSigningKey2026

# loggin (optional)
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.reactor.netty=INFO